package Network;
// Generated 02-Apr-2020 15:04:31 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * Links generated by hbm2java
 */
@Entity
public class Links  implements java.io.Serializable {

@Id
     private int id;
     private int source;
     private int destination;
     private String linkname;

    public Links() {
    }

    public Links(int id, int source, int destination, String linkname) {
       this.id = id;
       this.source = source;
       this.destination = destination;
       this.linkname = linkname;
    }
   
    public Links getLinks() {
        return this;
    }
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getSource() {
        return this.source;
    }
    
    public void setSource(int source) {
        this.source = source;
    }
    public int getDestination() {
        return this.destination;
    }
    
    public void setDestination(int destination) {
        this.destination = destination;
    }
    public String getLinkname() {
        return this.linkname;
    }
    
    public void setLinkname(String linkname) {
        this.linkname = linkname;
    }




}


